solution-templates:
  - solutionTemplateName: "testapp2-solution"
    baseconfig: "defaultbaseconfig.json"
    versions:
      - version: 0.3.0
        instanceName: "testapp2-inst-030"
        sites:
          - siteName: "houston"
            targets:
              - targetName: "hou-li-1"
                override:
                  ErrorThreshold: 0301
                  TemperatureRangeMax: "03011"
